services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  ldap:
    image: osixia/openldap:latest
    container_name: ldap_server
    restart: always
    environment:
      LDAP_ORGANISATION: Example
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_TLS: "True"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_ENFORCE: "False"
      LDAP_TLS_VERIFY_CLIENT: "never"
      LDAP_REPLICATION: "false"
      LDAP_CONFIGURATION_PAM: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldap/01-test-users.ldif:/ldif/01-test-users.ldif
      - ./ldap/init-ldap.sh:/init-ldap.sh
      - ./ldap/certs:/container/service/slapd/assets/certs
    entrypoint: ["/bin/bash", "/init-ldap.sh"]      
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap_admin
    restart: always
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap_server
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8080:80"
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: django_backend
    environment:
    - SECRET_KEY=${SECRET_KEY}
    - DEBUG=${DEBUG}
    - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - LDAP_SERVER_URI=${LDAP_SERVER_URI}
    - LDAP_BIND_DN=${LDAP_BIND_DN}
    - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
    - LDAP_USER_SEARCH_BASE=${LDAP_USER_SEARCH_BASE}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ldap

  frontend:
    build:
      context: ./booking-frontend
      dockerfile: Dockerfile.frontend
    container_name: react_frontend
    ports:
      - "3443:443"

volumes:
  ldap_data:
  ldap_config:
  postgres_data: