FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    libldap2-dev \
    libsasl2-dev \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

COPY DRF/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY DRF .

CMD ["gunicorn", "laundry_booking.wsgi:application", "--bind", "0.0.0.0:8000"]
