# Generated by Django 5.1.4 on 2025-03-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time_slot', models.CharField(max_length=20)),
                ('machine', models.IntegerField()),
                ('room', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
