# Generated by Django 5.1.4 on 2025-03-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('day', 'time_slot', 'machine')},
        ),
    ]
