# Generated by Django 5.1.4 on 2025-03-05 04:34

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[booking.models.validate_room]),
        ),
    ]
