# Generated by Django 5.1.4 on 2025-03-07 13:07

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_day_alter_booking_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(max_length=4, validators=[booking.validators.validate_room]),
        ),
    ]
