FROM node:18 as build

WORKDIR /app

COPY REACT/booking-frontend/.env.production .env.production

COPY REACT/booking-frontend/package*.json ./
RUN npm install

COPY REACT/booking-frontend ./
RUN npm run build