FROM node:18 as build

WORKDIR /app

COPY REACT/booking-frontend/package*.json ./
RUN npm install

COPY REACT/booking-frontend ./
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]