# Generated by Django 5.2.1 on 2025-06-04 12:37

import booking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[booking.validators.validate_date])),
                ('time_slot', models.CharField(max_length=20, validators=[booking.validators.validate_time_slot])),
                ('machine', models.IntegerField(validators=[booking.validators.validate_machine])),
                ('room', models.CharField(max_length=4, validators=[booking.validators.validate_room])),
            ],
            options={
                'unique_together': {('date', 'time_slot', 'machine')},
            },
        ),
    ]
